
language: java
jdk:
- oraclejdk8
before_install:
  - chmod +x mvnw
install:
- mvn install  -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
- mvnw install  -Dmaven.test.skip=true -Dmaven.javadoc.skip=true