before_install:
  - chmod +x mvnw
  
language: java
sudo: enabled
jdk:
- oraclejdk8
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V